[workspace]
members = ["grid_client", "grid_common", "grid_server"]
resolver = "2"

[workspace.dependencies]
serde = "1.0.225"
serde_json = "1.0.145"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
