name: Build and deploy
on:
  push:
    branches: [ $default-branch ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install tooling
      run: |
        cargo install cargo-binstall
        cargo binstall dioxus-cli
    - name: Lint
      run: cargo clippy --verbose
    - name: Test
      run: cargo test --verbose
    - name: Package
      run: dx bundle --platform web --package grid_client