name: Build and deploy
on:
  push:
    branches: [ $default-branch ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install tooling
      run: |
        cargo install cargo-binstall
        cargo binstall dioxus-cli
    - name: Lint
      run: cargo clippy --verbose
    - name: Test
      run: cargo test --verbose
    - name: Package
      run: dx bundle --platform web --package grid_client
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::491624026173:role/grid-online-s3-uploader
        aws-region: ca-central-1
    - name: Copy files
      run: |
        aws s3 sync target/dx/grid_client/release/web/public s3://grid.zootron.ca